In [1]:
# importing necessary libraries
import torch
import numpy as np

In [2]:
# Initializations of Tensors

# method 1 from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(x_data)

# method 2 from numpy array
x_np = torch.from_numpy(np.array(data))
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [3]:
# Method 3 from another tensor

# torch.ones_like(tensor) creates a tensor of the same shape as the input tensor and fills it with ones
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

# torch.rand_like(tensor) creates a tensor of the same shape as the input tensor and fills it with random values
# we can even change data type of the tensor

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor: \n {x_rand} \n")

# everytime you run this cell you will get different random values

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8300, 0.2421],
        [0.1523, 0.5145]]) 



In [4]:
# Shape is a tuple of tensor dimensions.
shape = (2, 3, )

random_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {random_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

# to get random tensor with integer values
random_int_tensor = torch.randint(0, 10, shape)
print(f"Random Integer Tensor: \n {random_int_tensor} \n")

Random Tensor: 
 tensor([[0.2836, 0.1565, 0.5107],
        [0.4226, 0.4163, 0.4247]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

Random Integer Tensor: 
 tensor([[8, 0, 5],
        [2, 2, 1]]) 



In [5]:
# attributes of a tensor
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [6]:
# check if CUDA is available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

/home/ayushraina/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


In [7]:
# Indexing and Slicings
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First Column ', tensor[:,0])
print('Last Column ', tensor[:,-1])

tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First Column  tensor([1., 1., 1., 1.])
Last Column  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [8]:
# Joining Tensors

# along column then dim = 1
t1 = torch.cat([tensor, tensor], dim = 1)
print("Column Wise Concatenated", t1)

# along row then dim = 0
t2 = torch.cat([tensor, tensor], dim = 0)
print("Row wise Concatenated",t2)

Column Wise Concatenated tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])
Row wise Concatenated tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
# Arithmetic Operations

# @ for matrix multiplication
data = [[1, 2], [3, 4]]
x = torch.tensor(data)

# Below two operations calculate the matrix multiplication
print("matrix multiplication is: ")
print(x @ x)
print(x.matmul(x))

matrix multiplication is: 
tensor([[ 7, 10],
        [15, 22]])
tensor([[ 7, 10],
        [15, 22]])


In [10]:
# Element wise multiplication
print(x * x)
print(x.mul(x))

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


In [11]:
# Single element tensor
agg = x.sum()
print(agg)

# to convert into a numerical value use item()
agg_item = agg.item()
print(agg_item)

tensor(10)
10


In [12]:
# Some Inplace operations
x = torch.tensor([[1, 2], [3, 4]])
print("Before Inplace operation: ")
print(x)
x.add_(5)
print("After Inplace operation: ")
print(x)

Before Inplace operation: 
tensor([[1, 2],
        [3, 4]])
After Inplace operation: 
tensor([[6, 7],
        [8, 9]])


In [13]:
# Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

# Tensor to NumPy array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [14]:
# changing one will change another
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

# same happend with numpy to tensor

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
